### ISSUE TITLE
Exiftool Description field

### ISSUE THREAD

**Issue by jarodium** [cobraz/xmp#1]
Hello there

With exiftool I do this:

exiftool -xmp:description-de='k&uuml;hl' -E dst.jpg
exiftool -xmp:description-en='hello world' -E dst.jpg

Your class does its job by returning the two values, but they are not keyed with de and en.

A sample output with 
exiftool dst.jpg

returns
Description (de)
Description (en)

Can the class account for those cases?

**Comment by simenandre** [comment]
Yes! Do you want to make a pull request to the class as such?

**Comment by jarodium** [comment]
Done. Thank you for the merge. Hopefully the algorithm for the patch will be improved by anyone which has more regex proeficciency than me, but at this time it will work. 
I'm working know on a function which will unescape the escapeshellcmd strings but that part will be easier to do.
